name: Flunt CI

on:
  push:
    branches:
      - develop
      - main
      - "releases/**"
  pull_request:
    branches:
      - develop
      - main
      - "releases/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Code quality analyzer
        run: composer run-script analyze

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test
        run: composer run-script test
